ABLATION_EXPERIMENTS = {
    'ablation_224_densevlm_nosne_noprompt': {
        'name': 'ablation_224_densevlm_nosne_noprompt',
        'desc': '224 + EVA02 + NoSNE + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_densevlm_sne_noprompt': {
        'name': 'ablation_224_densevlm_sne_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-proj) + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_densevlm_sne_prompt': {
        'name': 'ablation_224_densevlm_sne_prompt',
        'desc': '224 + EVA02 + SNE(pixel-proj) + Prompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_densevlm_sneotFalse_noprompt': {
        'name': 'ablation_224_densevlm_sneotFalse_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=F] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': False,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_densevlm_sneotTrue_noprompt': {
        'name': 'ablation_224_densevlm_sneotTrue_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_densevlm_sneotTrue_patchfpn_pisup_prompt_no_cos_mean': {
        'name': 'ablation_224_densevlm_sneotTrue_patchfpn_pisup_prompt_no_cos_mean',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + Prompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_densevlm_sneotFalse_noprompt': {
        'name': 'ablation_224_densevlm_sneotFalse_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=F] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': False,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_nosne_noprompt': {
        'name': 'ablation_224_eva02_nosne_noprompt',
        'desc': '224 + EVA02 + NoSNE + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_nosne_noprompt_nocd': {
        'name': 'ablation_224_eva02_nosne_noprompt_nocd',
        'desc': '224 + EVA02 + NoSNE + NoPrompt + NoCtxDec',
        'size': 224,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': False,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneBackboneCrossAttn_noprompt': {
        'name': 'ablation_224_eva02_sneBackboneCrossAttn_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-cross_attn) + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'cross_attn',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneBackboneProj_noprompt': {
        'name': 'ablation_224_eva02_sneBackboneProj_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-proj) + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneBackboneProj_noprompt_regE0eval': {
        'name': 'ablation_224_eva02_sneBackboneProj_noprompt_regE0eval',
        'desc': '224 + EVA02 + SNE(backbone-proj) + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'reg_e0_eval': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_snePixelProj_noprompt': {
        'name': 'ablation_224_eva02_snePixelProj_noprompt',
        'desc': '224 + EVA02 + SNE(pixel-proj) + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotFalse_noprompt': {
        'name': 'ablation_224_eva02_sneotFalse_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=F] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': False,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_noprompt': {
        'name': 'ablation_224_eva02_sneotTrue_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_output': True,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_noprompt': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T] + NoPrompt + PFPN',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_output': True,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,l2] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'l2',
        'ot_fuse_output': True,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,l2] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'l2',
        'ot_fuse_output': False,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_No_L2_mean': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_No_L2_mean',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,l2,mean] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'l2',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_output': False,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean_prob': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean_prob',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,Prob,mean] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_prior_mode': 'prob',
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean_prob_softunion': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean_prob_softunion',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,Prob,SoftU,mean] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_prior_mode': 'prob',
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'ot_softunion': True,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
        'ablation_512_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_prob_softunion_road_0.5': {
            'name': 'ablation_512_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_prob_softunion_road_0.5',
            'desc': '512 + EVA02 + SNE(backbone-ot)[Prior=T,Prob,SoftU,mean,T=0.5] + Prompt + PFPN + PiSup',
            'size': 512,
            'weight': 'EVA02',
            'sne': True,
            'sne_fusion_stage': 'backbone',
            'sne_mode': 'ot',
            'ot_prior': True,
            'ot_prior_mode': 'prob',
            'ot_cost_type': 'cos',
            'ot_fuse_mode': 'mean',
            'ot_fuse_output': False,
            'ot_softunion': True,
            'prompt': True,
            'context_decoder': True,
            'patch_fpn': True,
            'pi_sup': True,
            'csv_orfd': '',
            'csv_road3d': '', # Auto-search
        },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_max': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_max',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,max] + Prompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'max',
        'ot_fuse_output': False,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + Prompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_prob_softunion': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_prob_softunion',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,Prob,SoftU,mean] + Prompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_prior_mode': 'prob',
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'ot_softunion': True,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotTrue_patchfpn_xsam_pisup_noprompt': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_xsam_pisup_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T] + NoPrompt + PFPN(XSam) + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_output': True,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn_xsam': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_eva02_sneotFalse_noprompt': {
        'name': 'ablation_224_eva02_sneotFalse_noprompt',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=F] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': False,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_512_densevlm_nosne_prompt': {
        'name': 'ablation_512_densevlm_nosne_prompt',
        'desc': '512 + EVA02 + NoSNE + Prompt',
        'size': 512,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_512_densevlm_sne_prompt': {
        'name': 'ablation_512_densevlm_sne_prompt',
        'desc': '512 + EVA02 + SNE(pixel-proj) + Prompt',
        'size': 512,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_512_densevlm_sneotTrue_patchfpn_pisup_prompt_no_cos_mean': {
        'name': 'ablation_512_densevlm_sneotTrue_patchfpn_pisup_prompt_no_cos_mean',
        'desc': '512 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + Prompt + PFPN + PiSup',
        'size': 512,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_512_eva02_nosne_noprompt': {
        'name': 'ablation_512_eva02_nosne_noprompt',
        'desc': '512 + EVA02 + NoSNE + NoPrompt',
        'size': 512,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_512_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean': {
        'name': 'ablation_512_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean',
        'desc': '512 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + Prompt + PFPN + PiSup',
        'size': 512,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '', # Auto-search
        'csv_road3d': '',
    },
    'ablation_224_densevlm_nosne_noprompt_road': {
        'name': 'ablation_224_densevlm_nosne_noprompt_road',
        'desc': '224 + EVA02 + NoSNE + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_224_densevlm_sne_noprompt_road': {
        'name': 'ablation_224_densevlm_sne_noprompt_road',
        'desc': '224 + EVA02 + SNE(backbone-proj) + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_224_densevlm_sne_prompt_road': {
        'name': 'ablation_224_densevlm_sne_prompt_road',
        'desc': '224 + EVA02 + SNE(pixel-proj) + Prompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'exp_224_densevlm_sneotFalse_noprompt_road': {
        'name': 'exp_224_densevlm_sneotFalse_noprompt_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=F] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': False,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'exp_224_densevlm_sneotTrue_noprompt_road': {
        'name': 'exp_224_densevlm_sneotTrue_noprompt_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'exp_224_densevlm_sneotFalse_noprompt_road': {
        'name': 'exp_224_densevlm_sneotFalse_noprompt_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=F] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': False,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_224_eva02_nosne_noprompt_road': {
        'name': 'ablation_224_eva02_nosne_noprompt_road',
        'desc': '224 + EVA02 + NoSNE + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'exp_224_eva02_sneotFalse_noprompt_road': {
        'name': 'exp_224_eva02_sneotFalse_noprompt_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=F] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': False,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'exp_224_eva02_sneotTrue_noprompt_road': {
        'name': 'exp_224_eva02_sneotTrue_noprompt_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean_prob_softunion_road': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean_prob_softunion_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,Prob,SoftU,mean] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_prior_mode': 'prob',
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'ot_softunion': True,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean_road': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_noprompt_no_cos_mean_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + NoPrompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': False,
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_prob_softunion_road': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_prob_softunion_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,Prob,SoftU,mean] + Prompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_prior_mode': 'prob',
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'ot_softunion': True,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_road': {
        'name': 'ablation_224_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + Prompt + PFPN + PiSup',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'exp_224_eva02_sneotFalse_noprompt_road': {
        'name': 'exp_224_eva02_sneotFalse_noprompt_road',
        'desc': '224 + EVA02 + SNE(backbone-ot)[Prior=F] + NoPrompt',
        'size': 224,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': False,
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_512_densevlm_nosne_prompt_road': {
        'name': 'ablation_512_densevlm_nosne_prompt_road',
        'desc': '512 + EVA02 + NoSNE + Prompt',
        'size': 512,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_512_densevlm_sne_prompt_road': {
        'name': 'ablation_512_densevlm_sne_prompt_road',
        'desc': '512 + EVA02 + SNE(pixel-proj) + Prompt',
        'size': 512,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_512_eva02_nosne_noprompt_road': {
        'name': 'ablation_512_eva02_nosne_noprompt_road',
        'desc': '512 + EVA02 + NoSNE + NoPrompt',
        'size': 512,
        'weight': 'EVA02',
        'sne': False,
        'sne_fusion_stage': 'pixel',
        'sne_mode': 'proj',
        'prompt': False,
        'context_decoder': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_512_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_prob_softunion_road': {
        'name': 'ablation_512_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_prob_softunion_road',
        'desc': '512 + EVA02 + SNE(backbone-ot)[Prior=T,Prob,SoftU,mean] + Prompt + PFPN + PiSup',
        'size': 512,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_prior_mode': 'prob',
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'ot_softunion': True,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_512_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_road': {
        'name': 'ablation_512_eva02_sneotTrue_patchfpn_pisup_prompt_no_cos_mean_road',
        'desc': '512 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + Prompt + PFPN + PiSup',
        'size': 512,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': True,
        'prompt_cls_mode': 'hard',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_512_eva02_sneotTrue_patchfpn_pisup_promptSoft_no_cos_mean_road': {
        'name': 'ablation_512_eva02_sneotTrue_patchfpn_pisup_promptSoft_no_cos_mean_road',
        'desc': '512 + EVA02 + SNE(backbone-ot)[Prior=T,mean] + Prompt(Soft) + PFPN + PiSup',
        'size': 512,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'prompt': True,
        'prompt_cls_mode': 'soft',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
    'ablation_512_eva02_sneotTrue_patchfpn_pisup_promptSoft_no_cos_mean_prob_softunion_road_0.5': {
        'name': 'ablation_512_eva02_sneotTrue_patchfpn_pisup_promptSoft_no_cos_mean_prob_softunion_road_0.5',
        'desc': '512 + EVA02 + SNE(backbone-ot)[Prior=T,Prob,SoftU,mean,T=0.5] + Prompt(Soft) + PFPN + PiSup',
        'size': 512,
        'weight': 'EVA02',
        'sne': True,
        'sne_fusion_stage': 'backbone',
        'sne_mode': 'ot',
        'ot_prior': True,
        'ot_prior_mode': 'prob',
        'ot_cost_type': 'cos',
        'ot_fuse_mode': 'mean',
        'ot_fuse_output': False,
        'ot_softunion': True,
        'prompt': True,
        'prompt_cls_mode': 'soft',
        'context_decoder': True,
        'patch_fpn': True,
        'pi_sup': True,
        'csv_orfd': '',
        'csv_road3d': '', # Auto-search
    },
}
